blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/zkSync-Community-Hub/zkync-developers/discussions
      about: Please provide feedback, and ask questions here.
    - name: hardhat-zksync plugins documentation page
      url: https://era.zksync.io/docs/tools/hardhat/plugins.html
      about: Please refer to the documentation for immediate answers.