blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/zkSync-Community-Hub/zksync-developers/discussions
      about: Please provide feedback, and ask questions here.
    - name: hardhat-zksync plugins documentation page
      url: https://docs.zksync.io/build/tooling/hardhat/getting-started
      about: Please refer to the documentation for immediate answers.
