name: Change zksync2js release tag

on:
  push:
    branches:
      - main

jobs:
  change-zksync2js-release-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Setup environment
        run: yarn && yarn build

      - name: Change tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_NPM_MATTERLABS_AUTOMATION_TOKEN }}
        run: |
          npm dist-tag add @matterlabs/hardhat-zksync-zksync2js@0.0.1-beta.2 latest
          npm dist-tag add @matterlabs/hardhat-zksync-zksync2js@0.0.1-beta.0 beta

