name: Publish packages to npm

on:
  workflow_dispatch:
    inputs: 
      tag:
        required: true
        type: choice
        description: tag to publish
        default: legacy-ethers-v5
        options: 
          - legacy-ethers-v5
          - beta
          - alpha
          - latest

      package:
        required: true
        type: choice
        description: package to publish
        default: hardhat-zksync-deploy
        options: 
          - hardhat-zksync-deploy
          - hardhat-zksync-upgradable
          - hardhat-zksync-verify
          - hardhat-zksync-toolbox
          - hardhat-zksync-node
          - hardhat-zksync-chai-matchers

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Setup environment
        run: yarn && yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_NPM_MATTERLABS_AUTOMATION_TOKEN }}
        run: |
          npm publish @matterlabs/${{inputs.package}} --tag ${{ inputs.tag }} --workspace=packages/${{inputs.package}} --access=public

      - name: Create the MM Message
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh -R matter-labs/hardhat-zksync release view "$GITHUB_REF_NAME" --json tagName,body --template '## {{.tagName}} {{"\n"}}{{.body}}' > ./release_info
          jq --null-input --arg text "$(cat ./release_info)" '{"text": $text}' > mattermost.json

      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_USERNAME: "Hardhat Release Bot"
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_URL }}
